- name: check idempotency 
  hosts: local
  connection: local
  become: yes
  tasks:

  - name: user creation
    ansible.builtin.user:
     name: vedya

  - name: user creation
    ansible.builtin.user:
     name: Srivedya